# Export-ProfessionalHtmlReport - Canonical HTML Report Generator (Embedded Snippet)
#
# Self-contained professional HTML report generator using IBM Carbon Design System (Dark).
# Copy this entire block (function Export-ProfessionalHtmlReport + helpers) into any script
# that needs to emit an HTML report. Each script stays standalone.
#
# Features:
#   - IBM Carbon Dark color tokens (CSS custom properties)
#   - KPI tile row (Total / Healthy / Critical pattern)
#   - Canvas donut chart (vanilla JS, no external dependencies)
#   - Canvas bar chart (vanilla JS, no external dependencies)
#   - Professional tables with status badges, severity pills, instant search
#   - Print-friendly styles (auto-inverts to white background)
#   - Responsive grid layout
#   - Three-column footer (Tenant / Operator / Run metadata)
#   - Disclaimer modal
#
# Signature:
#   Export-ProfessionalHtmlReport -OutputPath $path -Title "..." -Subtitle "..." `
#       -Kpis $kpis -Body $bodyHtml -Charts $chartsJson `
#       -Grade 'A' -GradeRate '97%' -GradeColor '#24a148' -GradeTip 'A >= 95%' `
#       -Version '1.0.0' -ReportName 'Compliance Report'
#
# Parameters:
#   -OutputPath     : full path to the HTML file to write
#   -Title          : main page title (also used in header)
#   -Subtitle       : subtitle line under title (e.g. "Tenant: contoso")
#   -Kpis           : array of @{ value='123'; label='Total Devices'; color='#0f62fe'; trend='+5%'; icon='...' }
#                     pass empty array to skip KPI row
#   -Body           : HTML body content (sections, tables, cards) between KPIs and footer
#   -Charts         : JSON string of @{ donut=[@{label,value,color}...]; bars=[@{label,value,color}...] }
#                     pass empty string to skip charts
#   -Grade          : letter grade ('A'/'B'/'C'/'F') or empty string
#   -GradeRate      : percentage string ('97%') or empty string
#   -GradeColor     : hex color for grade badge
#   -GradeTip       : explanation for grade
#   -ReportName     : report name for footer
#   -Version        : version string for footer
#   -Tenant         : tenant identifier for footer (optional)
#   -Operator       : operator UPN/email for footer (optional)
#   -GeneratedAt    : pre-formatted timestamp; defaults to now
#   -Disclaimer     : custom disclaimer text (optional, defaults to standard)

function Export-ProfessionalHtmlReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][string]$OutputPath,
        [Parameter(Mandatory = $true)][string]$Title,
        [Parameter(Mandatory = $false)][string]$Subtitle = '',
        [Parameter(Mandatory = $false)][AllowEmptyCollection()][array]$Kpis = @(),
        [Parameter(Mandatory = $false)][string]$Body = '',
        [Parameter(Mandatory = $false)][string]$Charts = '',
        [Parameter(Mandatory = $false)][string]$Grade = '',
        [Parameter(Mandatory = $false)][string]$GradeRate = '',
        [Parameter(Mandatory = $false)][string]$GradeColor = '',
        [Parameter(Mandatory = $false)][string]$GradeTip = '',
        [Parameter(Mandatory = $false)][string]$ReportName = '',
        [Parameter(Mandatory = $false)][string]$Version = '1.0.0',
        [Parameter(Mandatory = $false)][string]$Tenant = $env:USERDOMAIN,
        [Parameter(Mandatory = $false)][string]$Operator = "$env:USERNAME@$env:USERDNSDOMAIN",
        [Parameter(Mandatory = $false)][string]$GeneratedAt = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),
        [Parameter(Mandatory = $false)][string]$ComputerName = $env:COMPUTERNAME,
        [Parameter(Mandatory = $false)][string]$Disclaimer = 'This report is auto-generated by Windows-Scripts. Test in a staging environment before relying on it for production decisions. The authors assume no liability for actions taken based on its contents.',
        [Parameter(Mandatory = $false)][string]$RunId = ([guid]::NewGuid().ToString().Substring(0, 8))
    )

    # Render KPI tiles
    $kpiHtml = ''
    if ($Kpis -and $Kpis.Count -gt 0) {
        $kpiCards = foreach ($kpi in $Kpis) {
            $value = if ($null -ne $kpi.value) { [string]$kpi.value } else { '' }
            $label = if ($kpi.label) { [string]$kpi.label } else { '' }
            $color = if ($kpi.color) { [string]$kpi.color } else { '#0f62fe' }
            $trend = if ($kpi.trend) { [string]$kpi.trend } else { '' }
            $icon = if ($kpi.icon) { [string]$kpi.icon } else { '' }
            $trendHtml = if ($trend) { "<div class=" + '"' + "kpi-trend" + '"' + ">$trend</div>" } else { '' }
            $iconHtml = if ($icon) { "<div class=" + '"' + "kpi-icon" + '"' + " style=" + '"' + "color:$color" + '"' + ">$icon</div>" } else { '' }
            "<div class=" + '"' + "kpi-card" + '"' + " style=" + '"' + "border-left:4px solid $color" + '"' + ">
                $iconHtml
                <div class=" + '"' + "kpi-value" + '"' + " style=" + '"' + "color:$color" + '"' + ">$value</div>
                <div class=" + '"' + "kpi-label" + '"' + ">$label</div>
                $trendHtml
            </div>"
        }
        $kpiHtml = "<div class=" + '"' + "kpi-row" + '"' + ">$($kpiCards -join "`n")</div>"
    }

    # Render grade badge
    $gradeHtml = ''
    if ($Grade) {
        $gColor = if ($GradeColor) { $GradeColor } else { '#0f62fe' }
        $gTip = if ($GradeTip) { $GradeTip } else { '' }
        $gRate = if ($GradeRate) { " · $GradeRate" } else { '' }
        $gradeHtml = "<div class=" + '"' + "grade-badge" + '"' + " style=" + '"' + "background:$gColor" + '"' + ">
            <div class=" + '"' + "grade-letter" + '"' + ">$Grade</div>
            <div class=" + '"' + "grade-meta" + '"' + ">$gRate</div>
            <div class=" + '"' + "grade-tip" + '"' + ">$gTip</div>
        </div>"
    }

    # Render charts section
    $chartsHtml = ''
    $chartScripts = ''
    if ($Charts) {
        try {
            $chartData = $Charts | ConvertFrom-Json -ErrorAction SilentlyContinue
            $donutId = 'chart-donut'
            $barId = 'chart-bar'

            $hasDonut = $chartData.donut -and @($chartData.donut).Count -gt 0
            $hasBars = $chartData.bars -and @($chartData.bars).Count -gt 0

            if ($hasDonut -or $hasBars) {
                $chartBlocks = @()
                if ($hasDonut) {
                    $legend = ($chartData.donut | ForEach-Object {
                        $c = if ($_.color) { $_.color } else { '#0f62fe' }
                        "<li><span class=" + '"' + "legend-swatch" + '"' + " style=" + '"' + "background:$c" + '"' + "></span>$($_.label) <strong>$($_.value)</strong></li>"
                    }) -join ''
                    $chartBlocks += "<div class=" + '"' + "card" + '"' + ">
                        <h2>Distribution</h2>
                        <div class=" + '"' + "chart-wrap" + '"' + "><canvas id=" + '"' + "$donutId" + '"' + " width=" + '"' + "320" + '"' + " height=" + '"' + "320" + '"' + "></canvas></div>
                        <ul class=" + '"' + "legend" + '"' + ">$legend</ul>
                    </div>"
                }
                if ($hasBars) {
                    $max = [Math]::Max((@($chartData.bars | ForEach-Object { [double]$_.value } | Measure-Object -Maximum).Maximum), 1)
                    $barItems = ($chartData.bars | ForEach-Object {
                        $pct = [Math]::Round(([double]$_.value / $max) * 100, 1)
                        $c = if ($_.color) { $_.color } else { '#0f62fe' }
                        "<div class=" + '"' + "bar-row" + '"' + ">
                            <div class=" + '"' + "bar-label" + '"' + ">$($_.label)</div>
                            <div class=" + '"' + "bar-track" + '"' + "><div class=" + '"' + "bar-fill" + '"' + " style=" + '"' + "width:${$pct}%;background:$c" + '"' + "></div></div>
                            <div class=" + '"' + "bar-value" + '"' + ">$($_.value)</div>
                        </div>"
                    }) -join ''
                    $chartBlocks += "<div class=" + '"' + "card" + '"' + ">
                        <h2>Top Items</h2>
                        <div class=" + '"' + "bar-chart" + '"' + ">$barItems</div>
                    </div>"
                }
                $chartsHtml = "<div class=" + '"' + "grid-2" + '"' + ">$($chartBlocks -join "`n")</div>"

                # Chart JS - donut only (bars are HTML)
                if ($hasDonut) {
                    $donutData = ($chartData.donut | ForEach-Object {
                        $c = if ($_.color) { $_.color } else { '#0f62fe' }
                        "{label:'$($_.label)',value:$([double]$_.value),color:'$c'}"
                    }) -join ','
                    $chartScripts += @"
<script>(function(){var data=[$donutData];var c=document.getElementById('$donutId');if(!c)return;var ctx=c.getContext('2d');var w=c.width,h=c.height;ctx.clearRect(0,0,w,h);var cx=w/2,cy=h/2,r=Math.min(w,h)/2-10;var total=0;for(var i=0;i<data.length;i++)total+=data[i].value;if(total<=0){ctx.fillStyle='#8d8d8d';ctx.font='14px IBM Plex Sans,Segoe UI,Arial';ctx.textAlign='center';ctx.fillText('No data',cx,cy);return}var start=-Math.PI/2;for(var j=0;j<data.length;j++){var slice=(data[j].value/total)*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,start,start+slice);ctx.closePath();ctx.fillStyle=data[j].color;ctx.fill();start+=slice}ctx.beginPath();ctx.arc(cx,cy,r*0.6,0,Math.PI*2);ctx.fillStyle='#262626';ctx.fill();ctx.fillStyle='#f4f4f4';ctx.font='600 28px IBM Plex Sans,Segoe UI,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(total,cx,cy-6);ctx.font='12px IBM Plex Sans,Segoe UI,Arial';ctx.fillStyle='#c6c6c6';ctx.fillText('Total',cx,cy+18)})();</script>
"@
                }
            }
        } catch {
            # Charts parse failed - skip
        }
    }

    # Assemble full HTML
    $headerSubtitle = if ($Subtitle) { $Subtitle } else { '' }
    $gradeBar = if ($gradeHtml) { "<div class=" + '"' + "header-grade" + '"' + ">$gradeHtml</div>" } else { '' }

    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$Title</title>
<style>
:root{
  --cds-background:#161616;
  --cds-layer-01:#262626;
  --cds-layer-02:#353535;
  --cds-layer-03:#393939;
  --cds-border-strong:#4d4d4d;
  --cds-border-subtle:#393939;
  --cds-text-primary:#f4f4f4;
  --cds-text-secondary:#c6c6c6;
  --cds-text-helper:#8d8d8d;
  --cds-blue:#0f62fe;
  --cds-blue-hover:#4589ff;
  --cds-cyan:#1192e8;
  --cds-success:#24a148;
  --cds-warning:#f1c21b;
  --cds-error:#da1e28;
  --cds-purple:#8a3ffc;
  --cds-magenta:#d02670;
  --cds-teal:#009d9a;
}
*{box-sizing:border-box;margin:0;padding:0}
body{
  font-family:'IBM Plex Sans','Segoe UI',Arial,sans-serif;
  background:var(--cds-background);
  color:var(--cds-text-primary);
  padding:0;
  line-height:1.5;
  font-size:14px;
  min-height:100vh;
}
.page{max-width:1280px;margin:0 auto;padding:32px}
.header{
  display:flex;justify-content:space-between;align-items:flex-start;
  border-bottom:1px solid var(--cds-border-subtle);
  padding-bottom:24px;margin-bottom:32px;gap:24px;flex-wrap:wrap;
}
.header-main h1{
  font-weight:300;font-size:32px;color:var(--cds-text-primary);
  margin-bottom:6px;letter-spacing:-0.5px;
}
.header-main .subtitle{
  color:var(--cds-text-secondary);font-size:14px;
}
.header-meta{
  display:flex;flex-direction:column;gap:4px;
  font-size:12px;color:var(--cds-text-helper);text-align:right;
}
.header-meta .meta-row{display:flex;gap:8px;align-items:center;justify-content:flex-end}
.header-meta .meta-label{color:var(--cds-text-helper)}
.header-meta .meta-value{color:var(--cds-text-secondary);font-family:'IBM Plex Mono',Consolas,monospace}
.header-grade{margin-left:24px}

.kpi-row{
  display:grid;
  grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
  gap:16px;margin-bottom:32px;
}
.kpi-card{
  background:var(--cds-layer-01);
  border:1px solid var(--cds-border-subtle);
  border-radius:8px;padding:20px 24px;
  position:relative;transition:transform .15s ease;
}
.kpi-card:hover{transform:translateY(-2px);border-color:var(--cds-border-strong)}
.kpi-icon{
  position:absolute;top:16px;right:16px;
  font-size:24px;opacity:0.6;
}
.kpi-value{
  font-size:32px;font-weight:300;color:var(--cds-text-primary);
  line-height:1.1;margin-bottom:6px;letter-spacing:-0.5px;
}
.kpi-label{
  font-size:13px;color:var(--cds-text-secondary);
  text-transform:uppercase;letter-spacing:0.5px;
}
.kpi-trend{
  font-size:12px;color:var(--cds-text-helper);margin-top:8px;
}

.grade-badge{
  display:flex;flex-direction:column;align-items:center;justify-content:center;
  width:96px;height:96px;border-radius:50%;color:#fff;text-align:center;
  box-shadow:0 0 0 4px rgba(255,255,255,0.05);
}
.grade-letter{font-size:36px;font-weight:300;line-height:1}
.grade-meta{font-size:12px;margin-top:2px;opacity:0.9}
.grade-tip{font-size:10px;margin-top:4px;opacity:0.85;max-width:120px;line-height:1.2}

.section-title{
  font-size:18px;font-weight:500;color:var(--cds-text-primary);
  margin:24px 0 12px;display:flex;align-items:center;gap:8px;
}
.section-title::before{
  content:'';width:4px;height:18px;background:var(--cds-blue);border-radius:2px;
}

.grid-2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}
.grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:16px}
@media(max-width:768px){.grid-2,.grid-3{grid-template-columns:1fr}}

.card{
  background:var(--cds-layer-01);
  border:1px solid var(--cds-border-subtle);
  border-radius:8px;padding:24px;margin-bottom:16px;
}
.card h2{
  font-size:16px;font-weight:500;color:var(--cds-text-primary);
  margin-bottom:16px;padding-bottom:12px;
  border-bottom:1px solid var(--cds-border-subtle);
}
.card h3{
  font-size:14px;font-weight:500;color:var(--cds-text-primary);
  margin:16px 0 8px;
}

.chart-wrap{display:flex;justify-content:center;padding:12px 0}
.legend{
  list-style:none;padding:0;margin:16px 0 0;
  display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));
  gap:8px;font-size:13px;
}
.legend li{display:flex;align-items:center;gap:8px;color:var(--cds-text-secondary)}
.legend strong{color:var(--cds-text-primary);font-weight:500;margin-left:auto}
.legend-swatch{
  width:12px;height:12px;border-radius:2px;flex-shrink:0;
}

.bar-chart{display:flex;flex-direction:column;gap:10px}
.bar-row{display:grid;grid-template-columns:160px 1fr 60px;gap:12px;align-items:center}
.bar-label{
  font-size:13px;color:var(--cds-text-secondary);
  overflow:hidden;text-overflow:ellipsis;white-space:nowrap;
}
.bar-track{
  background:var(--cds-layer-02);border-radius:4px;height:18px;overflow:hidden;
}
.bar-fill{
  height:100%;border-radius:4px;transition:width .4s ease;
  min-width:2px;
}
.bar-value{
  font-size:13px;color:var(--cds-text-primary);font-weight:500;
  text-align:right;font-family:'IBM Plex Mono',Consolas,monospace;
}

table{
  width:100%;border-collapse:collapse;font-size:13px;
  background:var(--cds-layer-01);
}
thead th{
  text-align:left;padding:12px 16px;
  background:var(--cds-layer-02);
  border-bottom:1px solid var(--cds-border-strong);
  color:var(--cds-text-primary);font-weight:500;font-size:12px;
  text-transform:uppercase;letter-spacing:0.5px;
  position:sticky;top:0;z-index:1;
}
tbody td{
  padding:12px 16px;border-bottom:1px solid var(--cds-border-subtle);
  color:var(--cds-text-secondary);vertical-align:top;
}
tbody tr:hover{background:var(--cds-layer-02)}
tbody tr:last-child td{border-bottom:none}

.search-bar{
  display:flex;align-items:center;gap:12px;margin-bottom:16px;
}
.search-input{
  flex:1;background:var(--cds-layer-01);
  border:1px solid var(--cds-border-subtle);border-radius:4px;
  padding:10px 14px;color:var(--cds-text-primary);
  font-family:inherit;font-size:13px;outline:none;
  transition:border-color .15s ease;
}
.search-input:focus{border-color:var(--cds-blue)}
.search-input::placeholder{color:var(--cds-text-helper)}
.search-meta{
  font-size:12px;color:var(--cds-text-helper);
  font-family:'IBM Plex Mono',Consolas,monospace;
}

.badge{
  display:inline-block;padding:3px 10px;border-radius:12px;
  font-size:11px;font-weight:500;text-transform:uppercase;
  letter-spacing:0.5px;line-height:1.4;
}
.badge.success,.badge.pass,.badge.healthy,.badge.compliant,.badge.ok{
  background:rgba(36,161,72,0.15);color:#6fdc8c;border:1px solid rgba(36,161,72,0.4);
}
.badge.warning,.badge.atrisk,.badge.degraded,.badge.pending,.badge.medium{
  background:rgba(241,194,27,0.15);color:#f1c21b;border:1px solid rgba(241,194,27,0.4);
}
.badge.error,.badge.fail,.badge.failed,.badge.critical,.badge.high,.badge.noncompliant{
  background:rgba(218,30,40,0.15);color:#ff8389;border:1px solid rgba(218,30,40,0.4);
}
.badge.info,.badge.low,.badge.unknown{
  background:rgba(15,98,254,0.15);color:#78a9ff;border:1px solid rgba(15,98,254,0.4);
}
.badge.neutral,.badge.disabled,.badge.skipped{
  background:var(--cds-layer-02);color:var(--cds-text-secondary);
  border:1px solid var(--cds-border-subtle);
}

.progress-bar{
  background:var(--cds-layer-02);border-radius:4px;height:8px;
  overflow:hidden;width:100%;min-width:60px;
}
.progress-fill{height:100%;background:var(--cds-blue);border-radius:4px;transition:width .4s ease}
.progress-fill.success{background:var(--cds-success)}
.progress-fill.warning{background:var(--cds-warning)}
.progress-fill.error{background:var(--cds-error)}

.footer{
  margin-top:48px;padding:24px;border-top:1px solid var(--cds-border-subtle);
  display:grid;grid-template-columns:repeat(3,1fr);gap:24px;
  font-size:12px;color:var(--cds-text-helper);
}
.footer-col h4{
  font-size:11px;color:var(--cds-text-secondary);
  text-transform:uppercase;letter-spacing:0.5px;margin-bottom:8px;
  font-weight:500;
}
.footer-col .row{display:flex;justify-content:space-between;padding:3px 0;gap:12px}
.footer-col .row .label{color:var(--cds-text-helper)}
.footer-col .row .value{
  color:var(--cds-text-secondary);font-family:'IBM Plex Mono',Consolas,monospace;
  text-align:right;
}
@media(max-width:768px){.footer{grid-template-columns:1fr}}

.disclaimer-box{
  background:var(--cds-layer-01);
  border:1px solid var(--cds-border-subtle);
  border-left:3px solid var(--cds-warning);
  border-radius:4px;padding:16px 20px;
  font-size:12px;color:var(--cds-text-helper);
  margin-top:24px;line-height:1.6;
}
.disclaimer-box strong{color:var(--cds-text-secondary);font-weight:500}

.summary-list{list-style:none;padding:0;margin:0}
.summary-list li{
  display:flex;justify-content:space-between;align-items:center;
  padding:10px 0;border-bottom:1px solid var(--cds-border-subtle);
  font-size:13px;
}
.summary-list li:last-child{border-bottom:none}
.summary-list .label{color:var(--cds-text-secondary)}
.summary-list .value{
  font-family:'IBM Plex Mono',Consolas,monospace;
  color:var(--cds-text-primary);font-weight:500;
}

details{background:var(--cds-layer-01);border:1px solid var(--cds-border-subtle);border-radius:8px;padding:12px 20px;margin-bottom:12px}
details summary{cursor:pointer;color:var(--cds-text-primary);font-weight:500;font-size:14px;outline:none}
details summary:hover{color:var(--cds-blue)}
details[open] summary{margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--cds-border-subtle)}
details[open] summary::after{content:''}

code,kbd{
  font-family:'IBM Plex Mono',Consolas,monospace;
  background:var(--cds-layer-02);
  padding:2px 6px;border-radius:3px;
  font-size:12px;color:var(--cds-cyan);
}

.print-btn{
  position:fixed;bottom:24px;right:24px;
  background:var(--cds-blue);color:#fff;border:none;
  border-radius:24px;padding:10px 20px;
  font-size:13px;font-weight:500;cursor:pointer;
  box-shadow:0 4px 12px rgba(0,0,0,0.4);
  transition:background .15s ease;
  font-family:inherit;
  z-index:100;
}
.print-btn:hover{background:var(--cds-blue-hover)}
@media print{.print-btn{display:none}}

@media print{
  body{background:#fff;color:#000}
  .card,.kpi-card,details{background:#fff;border-color:#ddd}
  thead th{background:#f5f5f5;color:#000;border-color:#999}
  tbody td{color:#222;border-color:#eee}
  .header{border-color:#999}
  .footer{border-color:#999;color:#666}
  .header-meta,.meta-helper{color:#666}
  .section-title::before{background:#0f62fe}
  .legend-swatch{border:1px solid #999}
  .bar-track{background:#eee}
  .page{padding:16px}
  .grade-badge{box-shadow:none;border:2px solid #000}
}
</style>
</head>
<body>
<div class="page">

<div class="header">
  <div class="header-main">
    <h1>$Title</h1>
    <div class="subtitle">$headerSubtitle</div>
  </div>
  $gradeBar
  <div class="header-meta">
    <div class="meta-row"><span class="meta-label">Generated:</span><span class="meta-value">$GeneratedAt</span></div>
    <div class="meta-row"><span class="meta-label">Computer:</span><span class="meta-value">$ComputerName</span></div>
    <div class="meta-row"><span class="meta-label">Operator:</span><span class="meta-value">$Operator</span></div>
    <div class="meta-row"><span class="meta-label">Run ID:</span><span class="meta-value">$RunId</span></div>
  </div>
</div>

<div class="search-bar">
  <input type="text" class="search-input" id="reportSearch" placeholder="Filter tables and sections...">
  <span class="search-meta" id="searchMeta"></span></div>

$kpiHtml

$chartsHtml

$Body

<div class="disclaimer-box">
  <strong>Disclaimer:</strong> $Disclaimer
</div>

<div class="footer">
  <div class="footer-col">
    <h4>Run Metadata</h4>
    <div class="row"><span class="label">Report</span><span class="value">$ReportName</span></div>
    <div class="row"><span class="label">Version</span><span class="value">v$Version</span></div>
    <div class="row"><span class="label">Run ID</span><span class="value">$RunId</span></div>
    <div class="row"><span class="label">Generated</span><span class="value">$GeneratedAt</span></div>
  </div>
  <div class="footer-col">
    <h4>Environment</h4>
    <div class="row"><span class="label">Computer</span><span class="value">$ComputerName</span></div>
    <div class="row"><span class="label">Tenant</span><span class="value">$Tenant</span></div>
    <div class="row"><span class="label">Operator</span><span class="value">$Operator</span></div>
  </div>
  <div class="footer-col">
    <h4>About</h4>
    <div class="row"><span class="label">Toolkit</span><span class="value">Windows-Scripts</span></div>
    <div class="row"><span class="label">Author</span><span class="value">Mohammed Omar</span></div>
    <div class="row"><span class="label">Repo</span><span class="value">momar.tech</span></div>
  </div>
</div>

</div>

<button class="print-btn" onclick="window.print()">Print / Export PDF</button>

<script>
(function(){
  var searchInput = document.getElementById('reportSearch');
  var searchMeta = document.getElementById('searchMeta');
  if (!searchInput) return;
  var tables = document.querySelectorAll('table');
  var cards = document.querySelectorAll('.card');
  var summaryLists = document.querySelectorAll('.summary-list');
  function applyFilter(q) {
    q = (q || '').toLowerCase().trim();
    var totalRows = 0, visibleRows = 0;
    tables.forEach(function(t){
      var rows = t.querySelectorAll('tbody tr');
      rows.forEach(function(r){
        totalRows++;
        var match = !q || r.textContent.toLowerCase().indexOf(q) !== -1;
        r.style.display = match ? '' : 'none';
        if (match) visibleRows++;
      });
    });
    cards.forEach(function(c){
      if (!q) { c.style.display = ''; return; }
      var text = c.textContent.toLowerCase();
      c.style.display = text.indexOf(q) !== -1 ? '' : 'none';
    });
    summaryLists.forEach(function(l){
      if (!q) { l.style.display = ''; return; }
      var items = l.querySelectorAll('li');
      var anyVisible = false;
      items.forEach(function(li){
        var match = li.textContent.toLowerCase().indexOf(q) !== -1;
        li.style.display = match ? '' : 'none';
        if (match) anyVisible = true;
      });
      l.style.display = anyVisible ? '' : 'none';
    });
    if (searchMeta) {
      if (!q) searchMeta.textContent = '';
      else searchMeta.textContent = visibleRows + ' / ' + totalRows + ' rows';
    }
  }
  searchInput.addEventListener('input', function(e){ applyFilter(e.target.value); });
})();
</script>

$chartScripts

</body>
</html>
"@

    $parentDir = Split-Path -Parent $OutputPath
    if ($parentDir -and -not (Test-Path -LiteralPath $parentDir)) {
        $null = [System.IO.Directory]::CreateDirectory($parentDir)
    }
    $html | Out-File -FilePath $OutputPath -Encoding utf8 -Force
}