<#
.TITLE
    Embed-Xaml - GZip+Base64 XAML embedder for Tier 3 (PSWrap) tools.

.SYNOPSIS
    Build step that compresses xaml\*.xaml into Base64 blobs and injects them into src\UiLoader.ps1.

.DESCRIPTION
    Scope:
    Encodes every .xaml file in the project's xaml folder as a UTF-8 GZip+Base64 blob and
    writes a marker-delimited $script:EmbeddedXaml hashtable region into the UiLoader script.
    At runtime Get-EmbeddedXaml decompresses the blob; if the region is missing it falls back
    to reading xaml\*.xaml from disk.
    Safety guarantees:
    Never deletes or modifies source .xaml files. Creates a timestamped .bak copy of
    UiLoader.ps1 before writing. Marker replacement is idempotent - re-running updates
    the existing region instead of duplicating it.
    Degradation behavior:
    Missing UiLoader.ps1 or no .xaml files produce a clear error and exit 1 without writing anything.
    Output contract:
    One line per embedded window (name + original/compressed size) plus a final summary.
    Exit 0 on success, 1 on failure.

.TAGS
    Build,Tier3,PSWrap,Xaml

.PLATFORM
    Windows

.PERMISSIONS
    None (local execution)

.AUTHOR
    AI Generated

.VERSION
    1.0.0

.CHANGELOG
    1.0.0 (2026-08-22)
    - Initial release - implements the PSWrap embedded-XAML build step referenced by file-architecture.md

.LASTUPDATE
    2026-08-22

.EXAMPLE
    .\Embed-Xaml.ps1 -ProjectRoot . -XamlDirName views -UiLoaderPath src\UiLoader.ps1
    Uses custom folder names for projects that deviate from the PSWrap default layout.

.EXAMPLE
    .\Embed-Xaml.ps1 -ProjectRoot C:\Tools\MyGuiTool
    Encodes all xaml\*.xaml from the project and injects them into src\UiLoader.ps1.

.NOTES
    - Runtime counterpart: Get-EmbeddedXaml decompresses with GZip and falls back to disk XAML
    - Exit codes: 0 = success, 1 = failure
    - Run after every .xaml change; the generated region is marked do-not-edit-by-hand
#>

#Requires -Version 5.1

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectRoot,

    [string]$XamlDirName = 'xaml',

    [string]$UiLoaderPath = 'src\UiLoader.ps1'
)

$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.IO.Compression

$xamlDir = Join-Path $ProjectRoot $XamlDirName
$loaderFile = Join-Path $ProjectRoot $UiLoaderPath

if (-not (Test-Path -LiteralPath $loaderFile)) {
    Write-Error "UiLoader not found: $loaderFile"
    exit 1
}

if (-not (Test-Path -LiteralPath $xamlDir)) {
    Write-Error "XAML directory not found: $xamlDir"
    exit 1
}

function ConvertTo-GzipBase64 {
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][string]$Text)

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $stream = New-Object System.IO.MemoryStream
    $gzip = New-Object System.IO.Compression.GZipStream($stream, [System.IO.Compression.CompressionLevel]::Optimal)
    try {
        $gzip.Write($bytes, 0, $bytes.Length)
    }
    finally {
        $gzip.Dispose()
    }
    return [Convert]::ToBase64String($stream.ToArray())
}

$xamlFiles = @(Get-ChildItem -LiteralPath $xamlDir -Filter '*.xaml' -File -ErrorAction Stop)
if ($xamlFiles.Count -eq 0) {
    Write-Error "No .xaml files found in $xamlDir"
    exit 1
}

$entries = foreach ($file in $xamlFiles) {
    $raw = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $encoded = ConvertTo-GzipBase64 -Text $raw
    $name = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    Write-Host ("Embedded {0}: {1} bytes -> {2} base64 chars" -f $file.Name, $raw.Length, $encoded.Length)
    "    '{0}' = '{1}'" -f $name, $encoded
}

$region = @(
    '# >>> EMBEDDED-XAML (generated by scripts/Embed-Xaml.ps1 - do not edit by hand) >>>',
    '$script:EmbeddedXaml = @{'
) + $entries + @(
    '}'
    '# <<< EMBEDDED-XAML <<<'
)

$content = Get-Content -LiteralPath $loaderFile -Raw -Encoding UTF8
$markerPattern = '(?s)# >>> EMBEDDED-XAML.*?# <<< EMBEDDED-XAML <<<'

if ($content -match $markerPattern) {
    $content = [regex]::Replace($content, $markerPattern, ($region -join "`r`n"), 1)
    $action = 'updated'
}
else {
    $content = $content.TrimEnd() + "`r`n`r`n" + ($region -join "`r`n") + "`r`n"
    $action = 'appended to'
}

$backup = "$loaderFile.bak"
Copy-Item -LiteralPath $loaderFile -Destination $backup -Force
[System.IO.File]::WriteAllText($loaderFile, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host ("UiLoader {0}: {1} ({2} window(s), backup at {3})" -f $action, $loaderFile, $xamlFiles.Count, $backup)
exit 0
