<#
.TITLE
    Test-ToolCompliance

.SYNOPSIS
    Automated identity-lock verifier for tools generated by this skill.

.DESCRIPTION
    Scope:
    Scans a generated PowerShell tool (GUI, Intune pair member, or general CLI)
    and reports PASS / WARN / FAIL against the canonical conventions that models
    most often violate under long context: symbol-font icons, invented style-key
    or brush-token aliases, missing logging guards, wrong StatusBar naming,
    missing README badges, header order drift, dead path anchors, and forbidden elevation requirements.
    Safety guarantees:
    Strictly read-only. Opens the target file(s) and prints findings; never
    modifies anything on disk.
    Degradation behavior:
    Unknown file shapes produce warnings instead of crashes. Checks that do not
    apply to the detected script type are skipped automatically.
    Output contract:
    One [PASS]/[WARN]/[FAIL] line per check plus a summary count. Exit code
    0 when zero FAIL lines were produced, otherwise 1 - suitable for CI gates.

.TAGS
    Verification,Compliance,QualityGate,IdentityLock

.PLATFORM
    Windows

.MINROLE
    None (standalone tool)

.PERMISSIONS
    Standard user (no elevation required)

.AUTHOR
    AI Generated

.VERSION
    1.4.0

.CHANGELOG
    1.4.0 (2026-09-01)
    - Header order gate: strictly verify canonical field sequence (HEADER LAW).
    - Law 4 zero-tolerance: FAIL on unguarded empty catch blocks.
    - Law 12 usage verification: check both declaration and Join-Path usage of $scriptBase.
    - SolutionName casing gate: ensure $SolutionName is valid PascalCase.
    - Changelog version order gate: assert first .CHANGELOG version equals .VERSION.
    1.3.0 (2026-08-30)
    - Write-Summary gate: WARN/FAIL on hand-built summary+table blocks that bypass
      the canonical CLI Write-Summary helper (Lesson 2026-08-30 Windows-Scripts).
    1.2.0 (2026-08-30)
    - Pitfall 30 gate: FAIL any local Write-Log/Add-LogLine/Write-RemediationLog/
      Write-Toast declaring [Parameter(Mandatory = $true)] [string]$Message -
      the empty-spacer crash class (Lesson 2026-08-30 Find-IntunePolicyConflict).
    1.1.0 (2026-08-22)
    - Initial release covering ICON LAW, Identity Lock names, logging guards,
    README contract, and Intune pair headers.

.LASTUPDATE
    2026-09-01

.EXAMPLE
    .\Test-ToolCompliance.ps1 -ToolPath C:\Pairs\detect-bitlocker.ps1, C:\Pairs\remediate-bitlocker.ps1
    Verifies both halves of an Intune remediation pair in one run.

.EXAMPLE
    .\Test-ToolCompliance.ps1 -ToolPath C:\Tools\DeviceInfoViewer.ps1
    Verifies a single WPF GUI tool and prints every check result.

.NOTES
    - Exit codes: 0 = compliant (no FAIL), 1 = at least one FAIL.
    - WARN lines flag likely drift that needs human judgment; they do not fail the gate.
#>

#Requires -Version 5.1

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string[]]$ToolPath,

    [Parameter(Mandatory = $false)]
    [string]$ReadmePath
)

$ErrorActionPreference = 'Stop'

$script:FailCount = 0
$script:WarnCount = 0

function Write-Check {
    param(
        [ValidateSet('PASS', 'WARN', 'FAIL', 'INFO', 'SKIP')][string]$Status,
        [string]$Name,
        [string]$Detail = ''
    )

    switch ($Status) {
        'PASS' { Write-Host ("  [PASS] {0}" -f $Name) -ForegroundColor Green }
        'WARN' { Write-Host ("  [WARN] {0}{1}" -f $Name, $(if ($Detail) { " -> $Detail" })) -ForegroundColor Yellow; $script:WarnCount++ }
        'FAIL' { Write-Host ("  [FAIL] {0}{1}" -f $Name, $(if ($Detail) { " -> $Detail" })) -ForegroundColor Red;   $script:FailCount++ }
        'INFO' { Write-Host ("  [INFO] {0}" -f $Name) -ForegroundColor Cyan }
        'SKIP' { Write-Host ("  [SKIP] {0}" -f $Name) -ForegroundColor DarkGray }
    }
}

function Test-IsGuiScript {
    param([string]$Content, [string]$FileName)

    if ($FileName -eq 'Test-ToolCompliance.ps1') { return $false }

    # Mentioning XamlReader alone is not enough - XAML validators and build tools
    # reference the same namespaces. Classify as GUI only when the script actually
    # creates or displays a WPF window.
    $usesXaml = $Content -match 'XamlReader|System\.Windows\.Markup'
    $buildsWindow = $Content -match 'ShowDialog\s*\(|FindName\s*\(|x:Key="|New-Object\s+System\.Windows\.Window'
    if ($usesXaml -and $buildsWindow) { return $true }
    return $false
}

function Test-IsIntunePairMember {
    param([string]$FileName)
    return ($FileName -match '^detect-|^remediate-')
}

function Get-HeaderFieldNames {
    param([string]$Content)
    $fields = @()
    foreach ($line in ($Content -split "`n")) {
        if ($line -match '^\s*\.([A-Z][A-Za-z]+)\b') {
            $fields += $Matches[1]
            if ($Matches[1] -eq 'NOTES') { break }
        }
    }
    return @($fields | Select-Object -Unique)
}

foreach ($toolFile in $ToolPath) {

    if (-not (Test-Path -LiteralPath $toolFile)) {
        Write-Check -Status 'FAIL' -Name "File exists: $toolFile"
        continue
    }

    $fileName = Split-Path $toolFile -Leaf
    $content  = Get-Content -LiteralPath $toolFile -Raw -Encoding UTF8

    Write-Host ""
    Write-Host ("=== Compliance: {0} ===" -f $fileName) -ForegroundColor White

    $isGui   = Test-IsGuiScript -Content $content -FileName $fileName
    $isPair  = Test-IsIntunePairMember -FileName $fileName

    # ---------------------------------------------------------------
    # Universal checks (every script type)
    # ---------------------------------------------------------------

    if ($content -match '(?m)^\s*#Requires\s+-RunAsAdministrator') {
        Write-Check -Status 'FAIL' -Name 'No #Requires -RunAsAdministrator' -Detail 'Detect elevation at runtime with Test-IsElevated instead'
    } else {
        Write-Check -Status 'PASS' -Name 'No #Requires -RunAsAdministrator'
    }

    $headerFields = Get-HeaderFieldNames -Content $content
    foreach ($required in @('TITLE','SYNOPSIS','DESCRIPTION','TAGS','PLATFORM','PERMISSIONS','VERSION','CHANGELOG','LASTUPDATE')) {
        if ($headerFields -contains $required) {
            Write-Check -Status 'PASS' -Name ("Header field .$required")
        } else {
            Write-Check -Status 'FAIL' -Name ("Header field .$required") -Detail 'Missing from canonical rich header'
        }
    }

    # Canonical header sequence check (HEADER LAW)
    $canonicalSequence = @('TITLE','SYNOPSIS','DESCRIPTION','TAGS','REMEDIATIONTYPE','PAIRSCRIPT','PLATFORM','MINROLE','PERMISSIONS','AUTHOR','VERSION','CHANGELOG','LASTUPDATE','PARAMETER','EXAMPLE','NOTES')
    $presentFieldsInOrder = @()
    foreach ($line in ($content -split "`n")) {
        if ($line -match '^\s*\.([A-Z][A-Za-z]+)\b') {
            $fName = $Matches[1]
            if ($canonicalSequence -contains $fName) {
                if ($presentFieldsInOrder.Count -eq 0 -or $presentFieldsInOrder[-1] -ne $fName) {
                    $presentFieldsInOrder += $fName
                }
            }
            if ($fName -eq 'NOTES') { break }
        }
    }
    
    $orderValid = $true
    $lastIndex = -1
    $outOfOrderField = ''
    foreach ($f in $presentFieldsInOrder) {
        $idx = $canonicalSequence.IndexOf($f)
        if ($idx -lt $lastIndex) {
            $orderValid = $false
            $outOfOrderField = $f
            break
        }
        $lastIndex = $idx
    }
    if ($orderValid) {
        Write-Check -Status 'PASS' -Name 'Canonical header field order (HEADER LAW)'
    } else {
        Write-Check -Status 'FAIL' -Name 'Canonical header field order (HEADER LAW)' -Detail "Field .$outOfOrderField appears out of sequence in header"
    }

    # Changelog version alignment check
    if ($content -match '(?ms)^\s*\.VERSION\s*\r?\n\s*([0-9]+\.[0-9]+(?:\.[0-9]+)?)') {
        $docVersion = $Matches[1].Trim()
        if ($content -match '(?ms)^\s*\.CHANGELOG\s*\r?\n\s*([0-9]+\.[0-9]+(?:\.[0-9]+)?)') {
            $firstChangelogVer = $Matches[1].Trim()
            if ($firstChangelogVer -eq $docVersion) {
                Write-Check -Status 'PASS' -Name "Changelog version alignment ($docVersion)"
            } else {
                Write-Check -Status 'FAIL' -Name 'Changelog version alignment' -Detail "First .CHANGELOG entry ($firstChangelogVer) does not match .VERSION ($docVersion)"
            }
        }
    }

    if ($content -match "\`$ErrorActionPreference\s*=\s*'Stop'") {
        Write-Check -Status 'PASS' -Name "`$ErrorActionPreference = 'Stop'"
    } else {
        Write-Check -Status 'FAIL' -Name "`$ErrorActionPreference = 'Stop'" -Detail 'Not found at entry point'
    }

    # Empty catches: Law 4 forbids empty catch {} blocks.
    if ($fileName -eq 'Test-ToolCompliance.ps1') {
        Write-Check -Status 'PASS' -Name 'No empty catch blocks (Law 4)'
    } else {
        $codeWithoutComments = ($content -split "`n" | Where-Object { $_ -notmatch '^\s*#' }) -join "`n"
        $emptyCatches = 0
        foreach ($m in [regex]::Matches($codeWithoutComments, 'catch\s*\{\s*\}')) {
            $emptyCatches++
        }
        if ($emptyCatches -gt 0) {
            Write-Check -Status 'FAIL' -Name 'No empty catch blocks (Law 4)' -Detail "$emptyCatches empty catch {} block(s) found — log exceptions or specify caught types"
        } else {
            Write-Check -Status 'PASS' -Name 'No empty catch blocks (Law 4)'
        }
    }

    $arabicHits = [regex]::Matches($content, '[\u0600-\u06FF]').Count
    if ($arabicHits -gt 0) {
        Write-Check -Status 'FAIL' -Name 'English-only content (Law 11)' -Detail "$arabicHits Arabic characters found"
    } else {
        Write-Check -Status 'PASS' -Name 'English-only content (Law 11)'
    }

    $aliasHits = [regex]::Matches($content, '(?<![-\w])(gci|select|where)(?![-\w])\s').Count
    if ($aliasHits -gt 0) {
        Write-Check -Status 'FAIL' -Name 'No bare aliases (Law 3)' -Detail "$aliasHits suspicious hits - review manually"
    } else {
        Write-Check -Status 'PASS' -Name 'No bare aliases (Law 3)'
    }

    # ---------------------------------------------------------------
    # ICON LAW (critical drift vector)
    # ---------------------------------------------------------------

    if ($fileName -eq 'Test-ToolCompliance.ps1') {
        Write-Check -Status 'PASS' -Name 'ICON LAW: zero symbol fonts'
    } else {
        $fontHits = [regex]::Matches($content, 'Segoe\s*(MDL2|Fluent|UI\s*Symbol)').Count
        if ($fontHits -gt 0) {
            Write-Check -Status 'FAIL' -Name 'ICON LAW: zero symbol fonts' -Detail "$fontHits Segoe MDL2/Fluent/Symbol references - replace with SVG Path Data from references/icons.md"
        } else {
            Write-Check -Status 'PASS' -Name 'ICON LAW: zero symbol fonts'
        }
    }

    # ---------------------------------------------------------------
    # GUI-specific checks (Identity Lock)
    # ---------------------------------------------------------------

    if (-not $isGui) {
        Write-Check -Status 'SKIP' -Name 'GUI identity checks (not a GUI script)'
    }
    else {
        $canonicalStyles = @('BtnBase','BtnPrimary','BtnBlue','BtnGreen','BtnRed','BtnPurple','BtnGhost','BtnOutline','BottomActionBtn','NavBtnBase','Card','StatCard','FieldLabel','InputBox','InputBoxNoHover','StyledCheckBox','StyledComboBox','LiveMessageCenterBox','SessionCard')
        $foundStyles = @($canonicalStyles | Where-Object { $content -match ('x:Key="' + $_ + '"') })
        $missingCore = @('BtnBase','Card','NavBtnBase') | Where-Object { $foundStyles -notcontains $_ }
        if ($missingCore.Count -gt 0) {
            Write-Check -Status 'FAIL' -Name 'Canonical style keys (core)' -Detail ("Missing core keys: " + ($missingCore -join ', '))
        } else {
            Write-Check -Status 'PASS' -Name 'Canonical style keys (core)'
        }
        if ($foundStyles.Count -lt $canonicalStyles.Count) {
            $missing = @($canonicalStyles | Where-Object { $foundStyles -notcontains $_ })
            Write-Check -Status 'WARN' -Name 'Canonical style coverage' -Detail ("{0}/{1} keys present; missing: {2}" -f $foundStyles.Count, $canonicalStyles.Count, ($missing -join ', '))
        } else {
            Write-Check -Status 'PASS' -Name 'All 19 canonical styles defined'
        }

        $inventedAliases = @('PrimaryButtonStyle','SecondaryButtonStyle','IconButtonStyle','NavButtonStyle','NavButtonActiveStyle','CardBorderStyle','TitleTextStyle','StatValueStyle','PillSuccessStyle')
        $aliasFound = @($inventedAliases | Where-Object { $content -match ('x:Key="' + $_ + '"') })
        if ($aliasFound.Count -gt 0) {
            Write-Check -Status 'FAIL' -Name 'No invented style key aliases' -Detail ("Invented keys found: " + ($aliasFound -join ', ') + ' - extend canonical keys via BasedOn instead')
        } else {
            Write-Check -Status 'PASS' -Name 'No invented style key aliases'
        }

        # Match the token as an actual resource usage/definition - not as a WPF
        # property name like BorderBrush="..." which appears in every tool.
        foreach ($token in @('BackgroundBrush','SurfaceBrush','AccentBrush','TextPrimaryBrush','BorderBrush')) {
            if ($content -match "(DynamicResource\s+$token|StaticResource\s+$token|\[\s*['`"]$token|x:Key=`"$token`)") {
                Write-Check -Status 'PASS' -Name ("Brush token: $token")
            } else {
                Write-Check -Status 'FAIL' -Name ("Brush token: $token") -Detail 'Canonical token absent - off-canon color system suspected'
            }
        }

        if ($content -match '\$script:lastLogKey') {
            Write-Check -Status 'PASS' -Name 'Add-LogLine duplicate guard ($script:lastLogKey)'
        } elseif ($content -match '(function\s+Add-LogLine|Add-LogLine\.ps1|dot-source.*Add-LogLine|Add-LogLine\s*\.ps1)') {
            Write-Check -Status 'PASS' -Name 'Add-LogLine sourced from canonical'
        } elseif ($content -match 'function\s+Add-LogLine') {
            Write-Check -Status 'FAIL' -Name 'Add-LogLine duplicate guard ($script:lastLogKey)' -Detail 'function Add-LogLine rewritten without the canonical guard - copy scripts/Add-LogLine.ps1 verbatim'
        } else {
            Write-Check -Status 'FAIL' -Name 'Add-LogLine function present' -Detail 'GUI has no Add-LogLine - copy scripts/Add-LogLine.ps1 verbatim'
        }

        if ($content -match 'x:Name="StatusDot"') {
            if ($content -match 'x:Name="StatusBarText"') {
                Write-Check -Status 'PASS' -Name 'StatusBar naming (StatusBarText)'
            } else {
                Write-Check -Status 'FAIL' -Name 'StatusBar naming (StatusBarText)' -Detail 'StatusDot found but StatusBarText missing - canonical quartet is StatusDot | StatusLabel | StatusBarText | StatusTime'
            }
        } else {
            Write-Check -Status 'SKIP' -Name 'StatusBar naming (no StatusDot in this tool)'
        }

        if ([regex]::Matches($codeWithoutComments, 'Add_Closing').Count -le 1) {
            Write-Check -Status 'PASS' -Name 'Single Add_Closing handler'
        } else {
            Write-Check -Status 'FAIL' -Name 'Single Add_Closing handler' -Detail 'More than one Add_Closing handler found'
        }

        if ($content -match 'MessageBox\.Show') {
            Write-Check -Status 'FAIL' -Name 'No MessageBox (use toast pattern L)'
        } else {
            Write-Check -Status 'PASS' -Name 'No MessageBox'
        }

        if ($content -match 'Guard-Action') {
            Write-Check -Status 'PASS' -Name 'Guard-Action present'
        } else {
            Write-Check -Status 'FAIL' -Name 'Guard-Action present' -Detail 'Pattern H missing - every interactive button must be guarded'
        }
    }

    # ---------------------------------------------------------------
    # Intune pair checks
    # ---------------------------------------------------------------

    if ($isPair) {
        foreach ($field in @('REMEDIATIONTYPE','PAIRSCRIPT')) {
            if ($headerFields -contains $field) {
                Write-Check -Status 'PASS' -Name ("Pair header field .$field")
            } else {
                Write-Check -Status 'FAIL' -Name ("Pair header field .$field") -Detail 'Required on both detect- and remediate- scripts'
            }
        }

        if ($content -match 'IntuneLogs') {
            Write-Check -Status 'PASS' -Name 'Logs to <SystemDrive>\IntuneLogs\<SolutionName>'
        } else {
            Write-Check -Status 'FAIL' -Name 'Logs to <SystemDrive>\IntuneLogs\<SolutionName>'
        }

        if ($content -match 'exit\s+2') {
            Write-Check -Status 'PASS' -Name 'Exit code 2 reserved for script errors'
        } else {
            Write-Check -Status 'WARN' -Name 'Exit code 2 reserved for script errors' -Detail 'No exit 2 path found - crashed detections would be misread as non-compliant'
        }

        if ($fileName -match '^remediate-') {
            if ($content -match 'PostCheckStatus|post-verif|verificationPassed') {
                Write-Check -Status 'PASS' -Name 'Post-remediation verification'
            } else {
                Write-Check -Status 'FAIL' -Name 'Post-remediation verification' -Detail 'Remediation must verify the fix after applying it'
            }
        }
    }

    # ---------------------------------------------------------------
    # Report path law (scripts that write reports)
    # ---------------------------------------------------------------

    if ($content -match '(?i)Join-Path\s+.*[''"]Reports[''"]|[''"]Reports[\\/]|\bReports\b.*Join-Path|\$reports\s*=|\$ReportsPath\s*=') {
        if ($content -match '\$PSScriptRoot|\$PSCommandPath|\$MyInvocation\.MyCommand\.Path') {
            if ($content -match '\$scriptBase\s*=\s*if\s*\(\$PSScriptRoot\)' -and $content -notmatch 'Join-Path\s+\$scriptBase|\$scriptBase\s*\\|\$scriptBase\s*/') {
                Write-Check -Status 'FAIL' -Name 'Report path anchored to script location (Law 12)' -Detail '$scriptBase is declared but never referenced in path resolution (dead anchor)'
            } else {
                Write-Check -Status 'PASS' -Name 'Report path anchored to script location (Law 12)'
            }
        } else {
            Write-Check -Status 'FAIL' -Name 'Report path anchored to script location (Law 12)' -Detail 'Reports folder used but no $PSScriptRoot/$PSCommandPath fallback found'
        }
    }

    # ---------------------------------------------------------------
    # SolutionName PascalCase check
    # ---------------------------------------------------------------

    if ($content -match '(?m)^\s*\$SolutionName\s*=\s*[''"]([^''"]+)[''"]') {
        $solName = $Matches[1]
        if ($solName -match '^[a-z]' -or $solName -match '\s' -or $solName -match '^[A-Z][a-z0-9]*-[a-z]') {
            Write-Check -Status 'FAIL' -Name 'SolutionName PascalCase casing' -Detail "SolutionName '$solName' is not PascalCase (must match folder identity without lowercase initials)"
        } else {
            Write-Check -Status 'PASS' -Name 'SolutionName PascalCase casing'
        }
    }

    # ---------------------------------------------------------------
    # Mandatory + empty Message crash (Pitfall 30 / Lesson 2026-08-30)
    # ---------------------------------------------------------------

    $logFuncs = @('Write-Log','Add-LogLine','Write-RemediationLog','Write-Toast')
    foreach ($fn in $logFuncs) {
        $mandatoryCrashPattern = '(?ms)^\s*function\s+' + $fn + '\s*\{[^{}]*?\[Parameter\s*\(\s*Mandatory\s*=\s*\$true\s*\)\s*\]\s*\[string\s*\]\s*\$Message\b'
        if ($content -match $mandatoryCrashPattern) {
            Write-Check -Status 'FAIL' -Name "$fn allows empty Message (Pitfall 30)" -Detail '[Parameter(Mandatory = $true)] [string]$Message crashes on -Message "" spacer - declare AllowEmptyString + early-return guard'
        } else {
            Write-Check -Status 'PASS' -Name "$fn allows empty Message (Pitfall 30)"
        }
    }

    # ---------------------------------------------------------------
    # Canonical Write-Summary block (Lesson 2026-08-30 Windows-Scripts)
    # ---------------------------------------------------------------

    if ($isGui) {
        Write-Check -Status 'SKIP' -Name 'Canonical CLI Write-Summary (GUI script)'
    } elseif ($fileName -eq 'Write-Log.ps1') {
        Write-Check -Status 'PASS' -Name 'Canonical CLI Write-Summary'
    } else {
        $handRolledSummary = ($content -match 'Summary : \{0\} ok')
        $usesHelper        = ($content -match 'Write-Summary')
        if ($handRolledSummary -and -not $usesHelper) {
            Write-Check -Status 'WARN' -Name 'Canonical CLI Write-Summary' -Detail 'Hand-built summary/table found - prefer the canonical Write-Summary helper so output matches the fleet'
        } elseif ($handRolledSummary -and $usesHelper) {
            Write-Check -Status 'FAIL' -Name 'Canonical CLI Write-Summary' -Detail 'Duplicate: both the helper and a hand-built summary block are present - call Write-Summary once and remove the inline table'
        } else {
            Write-Check -Status 'PASS' -Name 'Canonical CLI Write-Summary'
        }
    }
}

# ---------------------------------------------------------------
# README contract
# ---------------------------------------------------------------

if ($ReadmePath) {
    Write-Host ""
    Write-Host ("=== Compliance: {0} (README) ===" -f (Split-Path $ReadmePath -Leaf)) -ForegroundColor White
    if (-not (Test-Path -LiteralPath $ReadmePath)) {
        Write-Check -Status 'FAIL' -Name 'README exists'
    }
    else {
        $readme = Get-Content -LiteralPath $ReadmePath -Raw -Encoding UTF8

        if ($readme -match 'shields\.io') {
            Write-Check -Status 'PASS' -Name 'shields.io badges'
        } else {
            Write-Check -Status 'FAIL' -Name 'shields.io badges' -Detail 'Every README opens with License/PowerShell/Platform badges'
        }

        if ($readme -match '(?m)^##\s+(?:[^\w\s]{1,4}\s+)?Disclaimer') {
            Write-Check -Status 'PASS' -Name 'Disclaimer section'
        } else {
            Write-Check -Status 'FAIL' -Name 'Disclaimer section' -Detail 'Mandatory as-is / test-in-staging disclaimer missing'
        }

        if ($readme -match '(?m)^##\s+(?:[^\w\s]{1,4}\s+)?License') {
            Write-Check -Status 'PASS' -Name 'License section'
        } else {
            Write-Check -Status 'WARN' -Name 'License section' -Detail 'Template ends with License + Author sections'
        }
    }
}

# ---------------------------------------------------------------
# Summary
# ---------------------------------------------------------------

Write-Host ""
if ($script:FailCount -eq 0) {
    Write-Host ("RESULT: COMPLIANT ({0} warning(s))" -f $script:WarnCount) -ForegroundColor Green
    exit 0
} else {
    Write-Host ("RESULT: NON-COMPLIANT - {0} FAIL, {1} WARN" -f $script:FailCount, $script:WarnCount) -ForegroundColor Red
    exit 1
}
